using SQLite;

//NOTE: using SQLite
//NOTE: using 'People.Models' namespace (autogenerated code just put it in 'People' namespace
//NOTE: all syntax inside '[]' is SQL-specific
namespace People.Models
{
    [Table("people")]
    public class Person
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        [MaxLength(250), Unique]
        public string Name { get; set; }
    }
}